/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HRManager;

import Login.CurrentUser;
import Login.DBCon;
import Login.Login;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ViewAllApplications extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllApplications
     */
    Connection con = null;
    public void LoadTable()
    {
        try {
            
         if (con == null){
         Class.forName("com.mysql.cj.jdbc.Driver");
        
            
            con = DBCon.connectDB();
         }
            String query = "Select * from application";
            Statement st = con.createStatement();
            ResultSet res;//
            res = st.executeQuery(query);
            
     
            /*while(res.next()){
            System.out.println(res.getString("username")+ " ");
            System.out.print(res.getString("password") + " ");
            System.out.print(res.getString("name") + " ");
            System.out.print(res.getString("salary") + " ");
            System.out.print(res.getString("designation"));
             }*/
            
            DefaultTableModel dtm = new DefaultTableModel();   
            String[] colName = {"ID","Name","Degree","Institution","Skills","Contact","Experience",};
            dtm.setColumnIdentifiers(colName);
            jTable1.setModel(dtm);
            
            
            PreparedStatement pst = con.prepareStatement("Select ID,Name,Degree,Institution,Skills,Contact,Experience from application ");
            ResultSet rs = pst.executeQuery();
            int i = 0;
            while (rs.next()) {
                
                
                String uname = rs.getString("ID");
                String name = rs.getString("name");
                String salary = rs.getString("degree");
                String designation = rs.getString("institution");
                String skills = rs.getString("skills");
                String contact = rs.getString("contact");
                String exp = rs.getString("experience");
                
                dtm.addRow(new Object[]{uname, name, salary, designation,skills,contact,exp});
                
                System.out.println(uname + " " + name + " " + salary + " " + designation + " " + skills);
                
                i++;
            
          }
            
            //con.close();
     }
        catch (SQLIntegrityConstraintViolationException ex) {
            
            System.out.println("Primary key SQLEXception");
            ex.printStackTrace();
        }
     catch(Exception exc)
     {
         System.out.println("SQLEXception");
            exc.printStackTrace();
     }
        
    }
    public ViewAllApplications() {
        initComponents();
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        appNameLabel = new javax.swing.JLabel();
        homeBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        menuPanel.setBackground(new java.awt.Color(46, 133, 243));

        homeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(46, 133, 243));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        appNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        appNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        appNameLabel.setText("WorkOtter");

        homeBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homeBtn1.setForeground(new java.awt.Color(46, 133, 243));
        homeBtn1.setText("Logout");
        homeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeBtn)
                .addGap(18, 18, 18)
                .addComponent(homeBtn1)
                .addGap(31, 31, 31))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appNameLabel)
                    .addComponent(homeBtn)
                    .addComponent(homeBtn1))
                .addGap(46, 46, 46))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRManager/viewallemployees.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Applicant Records");

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Nabeeha", null, "Project Manager", "12/10/2001", null, null},
                {"2", "Komal", null, "HR Manager", "12/10/2002", null, null},
                {"3", "Nisa", null, "Developer", "12/10/2003", null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Hiring_Status", "Age", "Degree", "Experience", "Recent Job"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(46, 143, 243));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Shortlist");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(46, 143, 243));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add New");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(46, 143, 243));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jButton3)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //shortlisted applications
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        
       
        if (row == -1)
        {
            String err = "Select a row to shortlist";
            JOptionPane.showMessageDialog(null, err);
        }
        else
            System.out.println("rows = " + row); 
        if (row!=-1) //row is -1 if nothing selected
        {
            Object username = dtm.getValueAt(row, 0);
            System.out.println("shortlisting = " + username); //yeh basically id hai
            
            try {
                PreparedStatement pst = con.prepareStatement("Select name,contact from application where id = ?");
                pst.setString(1,(String) username);
               ResultSet rs = pst.executeQuery();
               
               String name = null;
               String contact = null;
            while(rs.next()){
               System.out.println("SHORTLIST");
               name = rs.getString("name");
            contact = rs.getString("contact");
            }
            
            JTextField designation = new JTextField();
            JTextField hiringstatus = new JTextField();
            Object[] msg = {"Designation ",designation, "Hiring Status",hiringstatus };
            int option = JOptionPane.showConfirmDialog(null, msg, "Shortlisting Details", JOptionPane.OK_CANCEL_OPTION);
         if(designation.getText().equals("") || hiringstatus.getText().equals(""))
            {
                String msg1 = "One or more fields empty. try again.";
                JOptionPane.showMessageDialog(null, msg1);
                return;
            }
         
         if (!designation.getText().equals("Developer") && !designation.getText().equals("Project Manager"))
             {
                 JOptionPane.showMessageDialog(null, "Invalid designation!");
                return;
             }
         
            if (option == JOptionPane.OK_OPTION)
            {
                PreparedStatement p = con.prepareStatement("Insert into shortlisted(name,contact,designation,hiringstatus) values (?,?,?,?)");
                p.setString(1,name);
                p.setString(2,contact);
                
                String des = designation.getText();
                String hs = hiringstatus.getText();
                p.setString(3,des);
                p.setString(4,hs);
                p.execute();
            }
                   
                

            } 
            catch (SQLException ex) {
               
                System.out.println("\nDeletion exception");
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //Add New Applicant
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JTextField name = new JTextField();
        JTextField contact = new JTextField();
        JTextField degree = new JTextField();
        JTextField institution = new JTextField();
        JTextField cgpa = new JTextField();
        JTextField experience = new JTextField();
        JTextField skills = new JTextField();
        
        Object[] fields = {
            "Applicant Name:", name, 
            "Contact:", contact,
            "Recent Degree", degree,
            "Recent Institution", institution,
            "Graduating CGPA", cgpa,
            "Experience in Years", experience,
            "Skills", skills
        };
               
        int option = JOptionPane.showConfirmDialog(null, fields, "Applicant Details", JOptionPane.OK_CANCEL_OPTION);
        
        
        if (option == JOptionPane.OK_OPTION)
        {
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           
           String uname = name.getText();
            String pw = contact.getText();
            String nm = degree.getText();
            String des = institution.getText();
            String sal = cgpa.getText();
           String exp = experience.getText();
           String skill = skills.getText();
            if(uname.equals("") || pw.equals("") || des.equals("") || sal.equals("") || exp.equals("") || skill.equals(""))
            {
                String msg = "One or more fields empty. try again.";
                JOptionPane.showMessageDialog(null, msg);
                return;
            }
           model.addRow(new Object[]{uname, pw, nm,des,sal,exp,skill});
           
           String query = "Insert into application(name,contact,degree,institution, cgpa, experience,skills) values(?,?,?,?,?,?,?)";
            try {
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,uname);
                pst.setString(2,pw);
                pst.setString(3,nm);
                pst.setString(4,des);
                pst.setString(5,sal);
                pst.setString(6,exp);
                pst.setString(7,skill);
                
                pst.execute();
                
                LoadTable();
                
            } 
             catch(SQLIntegrityConstraintViolationException exc)
            {
                System.out.println("Primary ket exception adding new applicant");
                exc.printStackTrace();
            }
            catch (SQLException ex) {
                
                System.out.println("Exception while adding new applicant");
                ex.printStackTrace();
//Logger.getLogger(ManageEmployees.class.getName()).log(Level.SEVERE, null, ex);
            }

            
        } 
        
    }//GEN-LAST:event_jButton2ActionPerformed
//Delete Button
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        if (row == -1)
        {
            String err = "Select a row to delete";
            JOptionPane.showMessageDialog(null, err);
        }
        if (row!=-1) //row is -1 if nothing selected
        {
            Object username = dtm.getValueAt(row, 0); //Unique ID
            
            System.out.println("deleting = " + username);
            
            try {
                PreparedStatement pst = con.prepareStatement("Delete from application where id = ?");
                pst.setString(1, (String) username);
                
                pst.execute();
                
                LoadTable();
                
//PreparedStatement pst = con.prepareStatement("Select")
            } catch (SQLException ex) {
                //Logger.getLogger(ManageEmployees.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("\nDeletion exception applicant");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        
        HRManagerHomePage hp = new HRManagerHomePage();
        hp.show();
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void homeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtn1ActionPerformed
        // TODO add your handling code here:
        Login lgn = new Login();
        lgn.show();
        CurrentUser.logOut();
        dispose();
    }//GEN-LAST:event_homeBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewAllApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewAllApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewAllApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewAllApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewAllApplications().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton homeBtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
